export interface ServiceArea {
  code: string;
  name: string;
}

export interface LargeArea {
  code: string;
  large_service_area: ServiceArea;
  name: string;
  service_area: ServiceArea;
}

export interface MiddleArea {
  code: string;
  large_area: ServiceArea;
  large_service_area: ServiceArea;
  name: string;
  service_area: ServiceArea;
}

export interface SmallArea {
  code: string;
  large_area: ServiceArea;
  large_service_area: ServiceArea;
  middle_area: ServiceArea;
  name: string;
  service_area: ServiceArea;
}

export const largeServiceArea: ServiceArea[] = [
  { code: "SS10", name: "関東" },
  { code: "SS20", name: "関西" },
  { code: "SS30", name: "東海" },
  { code: "SS40", name: "北海道" },
  { code: "SS50", name: "東北" },
  { code: "SS60", name: "北陸・甲信越" },
  { code: "SS70", name: "中国" },
  { code: "SS80", name: "四国" },
  { code: "SS90", name: "九州・沖縄" },
];

export const largeArea: LargeArea[] = [
  {
    code: "Z011",
    large_service_area: { code: "SS10", name: "関東" },
    name: "東京",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Z012",
    large_service_area: { code: "SS10", name: "関東" },
    name: "神奈川",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Z013",
    large_service_area: { code: "SS10", name: "関東" },
    name: "埼玉",
    service_area: { code: "SA13", name: "埼玉" },
  },
  {
    code: "Z014",
    large_service_area: { code: "SS10", name: "関東" },
    name: "千葉",
    service_area: { code: "SA14", name: "千葉" },
  },
  {
    code: "Z015",
    large_service_area: { code: "SS10", name: "関東" },
    name: "茨城",
    service_area: { code: "SA15", name: "茨城" },
  },
  {
    code: "Z016",
    large_service_area: { code: "SS10", name: "関東" },
    name: "栃木",
    service_area: { code: "SA16", name: "栃木" },
  },
  {
    code: "Z017",
    large_service_area: { code: "SS10", name: "関東" },
    name: "群馬",
    service_area: { code: "SA17", name: "群馬" },
  },
  {
    code: "Z021",
    large_service_area: { code: "SS20", name: "関西" },
    name: "滋賀",
    service_area: { code: "SA21", name: "滋賀" },
  },
  {
    code: "Z022",
    large_service_area: { code: "SS20", name: "関西" },
    name: "京都",
    service_area: { code: "SA22", name: "京都" },
  },
  {
    code: "Z023",
    large_service_area: { code: "SS20", name: "関西" },
    name: "大阪",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Z024",
    large_service_area: { code: "SS20", name: "関西" },
    name: "兵庫",
    service_area: { code: "SA24", name: "兵庫" },
  },
  {
    code: "Z025",
    large_service_area: { code: "SS20", name: "関西" },
    name: "奈良",
    service_area: { code: "SA25", name: "奈良" },
  },
  {
    code: "Z026",
    large_service_area: { code: "SS20", name: "関西" },
    name: "和歌山",
    service_area: { code: "SA26", name: "和歌山" },
  },
  {
    code: "Z031",
    large_service_area: { code: "SS30", name: "東海" },
    name: "岐阜",
    service_area: { code: "SA31", name: "岐阜" },
  },
  {
    code: "Z032",
    large_service_area: { code: "SS30", name: "東海" },
    name: "静岡",
    service_area: { code: "SA32", name: "静岡" },
  },
  {
    code: "Z033",
    large_service_area: { code: "SS30", name: "東海" },
    name: "愛知",
    service_area: { code: "SA33", name: "愛知" },
  },
  {
    code: "Z034",
    large_service_area: { code: "SS30", name: "東海" },
    name: "三重",
    service_area: { code: "SA34", name: "三重" },
  },
  {
    code: "Z041",
    large_service_area: { code: "SS40", name: "北海道" },
    name: "北海道",
    service_area: { code: "SA41", name: "北海道" },
  },
  {
    code: "Z051",
    large_service_area: { code: "SS50", name: "東北" },
    name: "青森",
    service_area: { code: "SA51", name: "青森" },
  },
  {
    code: "Z052",
    large_service_area: { code: "SS50", name: "東北" },
    name: "岩手",
    service_area: { code: "SA52", name: "岩手" },
  },
  {
    code: "Z053",
    large_service_area: { code: "SS50", name: "東北" },
    name: "宮城",
    service_area: { code: "SA53", name: "宮城" },
  },
  {
    code: "Z054",
    large_service_area: { code: "SS50", name: "東北" },
    name: "秋田",
    service_area: { code: "SA54", name: "秋田" },
  },
  {
    code: "Z055",
    large_service_area: { code: "SS50", name: "東北" },
    name: "山形",
    service_area: { code: "SA55", name: "山形" },
  },
  {
    code: "Z056",
    large_service_area: { code: "SS50", name: "東北" },
    name: "福島",
    service_area: { code: "SA56", name: "福島" },
  },
  {
    code: "Z061",
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "新潟",
    service_area: { code: "SA61", name: "新潟" },
  },
  {
    code: "Z062",
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "富山",
    service_area: { code: "SA62", name: "富山" },
  },
  {
    code: "Z063",
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "石川",
    service_area: { code: "SA63", name: "石川" },
  },
  {
    code: "Z064",
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "福井",
    service_area: { code: "SA64", name: "福井" },
  },
  {
    code: "Z065",
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "山梨",
    service_area: { code: "SA65", name: "山梨" },
  },
  {
    code: "Z066",
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "長野",
    service_area: { code: "SA66", name: "長野" },
  },
  {
    code: "Z071",
    large_service_area: { code: "SS70", name: "中国" },
    name: "鳥取",
    service_area: { code: "SA71", name: "鳥取" },
  },
  {
    code: "Z072",
    large_service_area: { code: "SS70", name: "中国" },
    name: "島根",
    service_area: { code: "SA72", name: "島根" },
  },
  {
    code: "Z073",
    large_service_area: { code: "SS70", name: "中国" },
    name: "岡山",
    service_area: { code: "SA73", name: "岡山" },
  },
  {
    code: "Z074",
    large_service_area: { code: "SS70", name: "中国" },
    name: "広島",
    service_area: { code: "SA74", name: "広島" },
  },
  {
    code: "Z075",
    large_service_area: { code: "SS70", name: "中国" },
    name: "山口",
    service_area: { code: "SA75", name: "山口" },
  },
  {
    code: "Z081",
    large_service_area: { code: "SS80", name: "四国" },
    name: "徳島",
    service_area: { code: "SA81", name: "徳島" },
  },
  {
    code: "Z082",
    large_service_area: { code: "SS80", name: "四国" },
    name: "香川",
    service_area: { code: "SA82", name: "香川" },
  },
  {
    code: "Z083",
    large_service_area: { code: "SS80", name: "四国" },
    name: "愛媛",
    service_area: { code: "SA83", name: "愛媛" },
  },
  {
    code: "Z084",
    large_service_area: { code: "SS80", name: "四国" },
    name: "高知",
    service_area: { code: "SA84", name: "高知" },
  },
  {
    code: "Z091",
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "福岡",
    service_area: { code: "SA91", name: "福岡" },
  },
  {
    code: "Z092",
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "佐賀",
    service_area: { code: "SA92", name: "佐賀" },
  },
  {
    code: "Z093",
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "長崎",
    service_area: { code: "SA93", name: "長崎" },
  },
  {
    code: "Z094",
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "熊本",
    service_area: { code: "SA94", name: "熊本" },
  },
  {
    code: "Z095",
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "大分",
    service_area: { code: "SA95", name: "大分" },
  },
  {
    code: "Z096",
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "宮崎",
    service_area: { code: "SA96", name: "宮崎" },
  },
  {
    code: "Z097",
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "鹿児島",
    service_area: { code: "SA97", name: "鹿児島" },
  },
  {
    code: "Z098",
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "沖縄",
    service_area: { code: "SA98", name: "沖縄" },
  },
];

export const middleArea: MiddleArea[] = [
  {
    code: "Y005",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "銀座・有楽町・新橋・築地・月島",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y006",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "水道橋・飯田橋・神楽坂",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y007",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "お台場",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y010",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "東京・大手町・日本橋・人形町",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y013",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "四ツ谷・麹町・市ヶ谷・九段下",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y015",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "上野・御徒町・浅草",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y016",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "北千住・日暮里・葛飾・荒川",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y017",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "錦糸町・浅草橋・両国・亀戸",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y018",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "門前仲町・東陽町・木場・葛西",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y020",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "神田・神保町・秋葉原・御茶ノ水",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y025",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "品川･目黒･田町･浜松町･五反田",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y026",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "蒲田・大森・大田区",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y030",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "渋谷",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y035",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "原宿・青山・表参道",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y040",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "恵比寿・中目黒・代官山・広尾",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y045",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "赤坂・六本木・麻布十番・西麻布",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y046",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "自由が丘・田園調布",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y050",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "池袋",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y051",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "赤羽・王子・十条",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y055",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "新宿",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y056",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "新大久保・大久保",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y057",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "巣鴨・大塚・駒込",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y060",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "中野・高円寺・阿佐ヶ谷・方南町",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y070",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "下北沢・代々木上原",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y072",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "高田馬場",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y073",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "池尻大橋・三軒茶屋・駒沢大学",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y074",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "桜新町・用賀・二子玉川",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y075",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "祐天寺・学芸大学・都立大学",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y076",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "幡ヶ谷・笹塚・明大前・下高井戸",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y077",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "調布・府中・千歳烏山・仙川",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y078",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "経堂・千歳船橋",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y079",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "祖師ヶ谷大蔵・成城学園前",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y080",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "大井町･中延･旗の台･戸越･馬込",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y081",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "不動前・武蔵小山",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y082",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "雪が谷大塚・池上",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y083",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "武蔵小金井",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y084",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "武蔵小杉・元住吉・新丸子",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y085",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "新横浜・綱島・菊名・鴨居",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y086",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "大和・中央林間・長津田",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y087",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "新百合ヶ丘・登戸",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y088",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "国立・国分寺",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y089",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "青梅・昭島・小作・青梅線沿線",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y090",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "多摩センター・南大沢",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y100",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "吉祥寺・荻窪・三鷹",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y105",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "町田",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y110",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "八王子・立川",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y111",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "西武池袋線（石神井公園～秋津）",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y112",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "西武新宿線(中井～田無～東村山)",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y113",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "練馬・板橋・成増・江古田",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y114",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "都営三田線（新板橋～西高島平）",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y115",
    large_area: { code: "Z014", name: "千葉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "千葉・稲毛",
    service_area: { code: "SA14", name: "千葉" },
  },
  {
    code: "Y119",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "聖蹟桜ヶ丘・高幡不動・分倍河原",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y120",
    large_area: { code: "Z014", name: "千葉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "船橋･津田沼･市川･本八幡･中山",
    service_area: { code: "SA14", name: "千葉" },
  },
  {
    code: "Y121",
    large_area: { code: "Z014", name: "千葉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "南房総・館山",
    service_area: { code: "SA14", name: "千葉" },
  },
  {
    code: "Y122",
    large_area: { code: "Z014", name: "千葉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "千葉県その他",
    service_area: { code: "SA14", name: "千葉" },
  },
  {
    code: "Y125",
    large_area: { code: "Z014", name: "千葉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "柏・南柏・我孫子",
    service_area: { code: "SA14", name: "千葉" },
  },
  {
    code: "Y126",
    large_area: { code: "Z014", name: "千葉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "舞浜・浦安・行徳・妙典",
    service_area: { code: "SA14", name: "千葉" },
  },
  {
    code: "Y127",
    large_area: { code: "Z014", name: "千葉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "成田・佐倉",
    service_area: { code: "SA14", name: "千葉" },
  },
  {
    code: "Y128",
    large_area: { code: "Z014", name: "千葉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "海浜幕張",
    service_area: { code: "SA14", name: "千葉" },
  },
  {
    code: "Y129",
    large_area: { code: "Z014", name: "千葉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "蘇我・鎌取・茂原",
    service_area: { code: "SA14", name: "千葉" },
  },
  {
    code: "Y130",
    large_area: { code: "Z013", name: "埼玉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "大宮・さいたま新都心",
    service_area: { code: "SA13", name: "埼玉" },
  },
  {
    code: "Y131",
    large_area: { code: "Z013", name: "埼玉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "川口・西川口・蕨",
    service_area: { code: "SA13", name: "埼玉" },
  },
  {
    code: "Y132",
    large_area: { code: "Z013", name: "埼玉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "浦和・武蔵浦和",
    service_area: { code: "SA13", name: "埼玉" },
  },
  {
    code: "Y133",
    large_area: { code: "Z013", name: "埼玉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "熊谷・深谷・本庄",
    service_area: { code: "SA13", name: "埼玉" },
  },
  {
    code: "Y134",
    large_area: { code: "Z013", name: "埼玉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "東松山・坂戸",
    service_area: { code: "SA13", name: "埼玉" },
  },
  {
    code: "Y135",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "横浜",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y136",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "桜木町みなとみらい･関内･中華街",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y137",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "溝の口・たまプラーザ・青葉台",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y138",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "上大岡・杉田・新杉田・金沢文庫",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y139",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "センター北・南、仲町台・都筑区",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y140",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "川崎・鶴見",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y141",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "本厚木･相模大野･海老名･伊勢原",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y142",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "相模原・橋本・淵野辺",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y144",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "大船・戸塚・東戸塚・保土ヶ谷",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y145",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "藤沢・辻堂茅ヶ崎・平塚・湘南台",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y160",
    large_area: { code: "Z013", name: "埼玉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "秩父",
    service_area: { code: "SA13", name: "埼玉" },
  },
  {
    code: "Y161",
    large_area: { code: "Z013", name: "埼玉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "戸田",
    service_area: { code: "SA13", name: "埼玉" },
  },
  {
    code: "Y162",
    large_area: { code: "Z013", name: "埼玉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "上尾・北上尾・蓮田",
    service_area: { code: "SA13", name: "埼玉" },
  },
  {
    code: "Y163",
    large_area: { code: "Z013", name: "埼玉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "埼玉県その他",
    service_area: { code: "SA13", name: "埼玉" },
  },
  {
    code: "Y200",
    large_area: { code: "Z033", name: "愛知" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "名古屋（名古屋駅/西区/中村区）",
    service_area: { code: "SA33", name: "愛知" },
  },
  {
    code: "Y205",
    large_area: { code: "Z033", name: "愛知" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "栄ｷﾀ錦/伏見丸の内/泉/東桜/新栄",
    service_area: { code: "SA33", name: "愛知" },
  },
  {
    code: "Y210",
    large_area: { code: "Z033", name: "愛知" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "栄(ミナミ)/矢場町/大須/上前津",
    service_area: { code: "SA33", name: "愛知" },
  },
  {
    code: "Y215",
    large_area: { code: "Z033", name: "愛知" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "金山・神宮前・熱田区",
    service_area: { code: "SA33", name: "愛知" },
  },
  {
    code: "Y216",
    large_area: { code: "Z033", name: "愛知" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "鶴舞・八事・御器所",
    service_area: { code: "SA33", name: "愛知" },
  },
  {
    code: "Y220",
    large_area: { code: "Z033", name: "愛知" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "大曽根･千種･今池･池下･守山区",
    service_area: { code: "SA33", name: "愛知" },
  },
  {
    code: "Y221",
    large_area: { code: "Z033", name: "愛知" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "緑区・南区・天白区・瑞穂区",
    service_area: { code: "SA33", name: "愛知" },
  },
  {
    code: "Y222",
    large_area: { code: "Z033", name: "愛知" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "本山・覚王山・藤が丘",
    service_area: { code: "SA33", name: "愛知" },
  },
  {
    code: "Y223",
    large_area: { code: "Z033", name: "愛知" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "豊田市",
    service_area: { code: "SA33", name: "愛知" },
  },
  {
    code: "Y224",
    large_area: { code: "Z033", name: "愛知" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "中川区・港区",
    service_area: { code: "SA33", name: "愛知" },
  },
  {
    code: "Y225",
    large_area: { code: "Z033", name: "愛知" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "名古屋市その他",
    service_area: { code: "SA33", name: "愛知" },
  },
  {
    code: "Y230",
    large_area: { code: "Z032", name: "静岡" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "静岡駅周辺・葵区・駿河区",
    service_area: { code: "SA32", name: "静岡" },
  },
  {
    code: "Y231",
    large_area: { code: "Z032", name: "静岡" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "清水駅周辺～草薙",
    service_area: { code: "SA32", name: "静岡" },
  },
  {
    code: "Y250",
    large_area: { code: "Z071", name: "鳥取" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "鳥取県その他",
    service_area: { code: "SA71", name: "鳥取" },
  },
  {
    code: "Y260",
    large_area: { code: "Z072", name: "島根" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "島根県その他",
    service_area: { code: "SA72", name: "島根" },
  },
  {
    code: "Y270",
    large_area: { code: "Z021", name: "滋賀" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "滋賀県その他",
    service_area: { code: "SA21", name: "滋賀" },
  },
  {
    code: "Y271",
    large_area: { code: "Z021", name: "滋賀" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "草津市・守山市",
    service_area: { code: "SA21", name: "滋賀" },
  },
  {
    code: "Y280",
    large_area: { code: "Z034", name: "三重" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "三重県その他",
    service_area: { code: "SA34", name: "三重" },
  },
  {
    code: "Y290",
    large_area: { code: "Z025", name: "奈良" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "奈良県その他",
    service_area: { code: "SA25", name: "奈良" },
  },
  {
    code: "Y300",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "梅田",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y301",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "福島・野田",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y305",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "淀屋橋・本町・北浜・天満橋",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y310",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "京橋・天満・天六・南森町",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y315",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "心斎橋・なんば・南船場・堀江",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y325",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "天王寺",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y326",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "上本町・鶴橋",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y327",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "針中野･長居･西田辺･西成区･住吉",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y328",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "関目・千林・緑橋・深江橋",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y329",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "大阪市その他",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y350",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "堺・高石市・和泉市",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y355",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "高槻",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y356",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "茨木",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y357",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "泉大津･岸和田･泉佐野･りんくう",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y358",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "松原市･藤井寺市･富田林･南河内",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y360",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "江坂・西中島・新大阪・十三",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y361",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "東大阪市・八尾市・平野・大東市",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y365",
    large_area: { code: "Z022", name: "京都" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "烏丸御池・四条烏丸",
    service_area: { code: "SA22", name: "京都" },
  },
  {
    code: "Y370",
    large_area: { code: "Z024", name: "兵庫" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "神戸",
    service_area: { code: "SA24", name: "兵庫" },
  },
  {
    code: "Y371",
    large_area: { code: "Z024", name: "兵庫" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "明石",
    service_area: { code: "SA24", name: "兵庫" },
  },
  {
    code: "Y372",
    large_area: { code: "Z024", name: "兵庫" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "灘・東灘",
    service_area: { code: "SA24", name: "兵庫" },
  },
  {
    code: "Y373",
    large_area: { code: "Z024", name: "兵庫" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "須磨・垂水・西区・兵庫・長田",
    service_area: { code: "SA24", name: "兵庫" },
  },
  {
    code: "Y400",
    large_area: { code: "Z026", name: "和歌山" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "白浜・和歌山県その他",
    service_area: { code: "SA26", name: "和歌山" },
  },
  {
    code: "Y430",
    large_area: { code: "Z022", name: "京都" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "左京区・山科区",
    service_area: { code: "SA22", name: "京都" },
  },
  {
    code: "Y431",
    large_area: { code: "Z022", name: "京都" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "北区・上京区",
    service_area: { code: "SA22", name: "京都" },
  },
  {
    code: "Y432",
    large_area: { code: "Z022", name: "京都" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "河原町・木屋町",
    service_area: { code: "SA22", name: "京都" },
  },
  {
    code: "Y433",
    large_area: { code: "Z022", name: "京都" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "祇園・先斗町",
    service_area: { code: "SA22", name: "京都" },
  },
  {
    code: "Y434",
    large_area: { code: "Z022", name: "京都" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "四条大宮・西院・右京区・西京区",
    service_area: { code: "SA22", name: "京都" },
  },
  {
    code: "Y435",
    large_area: { code: "Z022", name: "京都" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "烏丸五条・京都駅周辺",
    service_area: { code: "SA22", name: "京都" },
  },
  {
    code: "Y437",
    large_area: { code: "Z022", name: "京都" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "伏見桃山・伏見区・京都市郊外",
    service_area: { code: "SA22", name: "京都" },
  },
  {
    code: "Y500",
    large_area: { code: "Z041", name: "北海道" },
    large_service_area: { code: "SS40", name: "北海道" },
    name: "すすきの",
    service_area: { code: "SA41", name: "北海道" },
  },
  {
    code: "Y501",
    large_area: { code: "Z041", name: "北海道" },
    large_service_area: { code: "SS40", name: "北海道" },
    name: "室蘭・登別・白老",
    service_area: { code: "SA41", name: "北海道" },
  },
  {
    code: "Y502",
    large_area: { code: "Z041", name: "北海道" },
    large_service_area: { code: "SS40", name: "北海道" },
    name: "富良野・その他北海道",
    service_area: { code: "SA41", name: "北海道" },
  },
  {
    code: "Y505",
    large_area: { code: "Z041", name: "北海道" },
    large_service_area: { code: "SS40", name: "北海道" },
    name: "札幌（札幌駅・大通）",
    service_area: { code: "SA41", name: "北海道" },
  },
  {
    code: "Y510",
    large_area: { code: "Z041", name: "北海道" },
    large_service_area: { code: "SS40", name: "北海道" },
    name: "麻生・北24条（北区・東区）",
    service_area: { code: "SA41", name: "北海道" },
  },
  {
    code: "Y511",
    large_area: { code: "Z041", name: "北海道" },
    large_service_area: { code: "SS40", name: "北海道" },
    name: "南郷・新札幌　白石・厚別・清田",
    service_area: { code: "SA41", name: "北海道" },
  },
  {
    code: "Y512",
    large_area: { code: "Z041", name: "北海道" },
    large_service_area: { code: "SS40", name: "北海道" },
    name: "琴似・円山公園　中央・西・手稲",
    service_area: { code: "SA41", name: "北海道" },
  },
  {
    code: "Y513",
    large_area: { code: "Z041", name: "北海道" },
    large_service_area: { code: "SS40", name: "北海道" },
    name: "平岸・澄川（豊平区・南区）",
    service_area: { code: "SA41", name: "北海道" },
  },
  {
    code: "Y530",
    large_area: { code: "Z041", name: "北海道" },
    large_service_area: { code: "SS40", name: "北海道" },
    name: "旭川",
    service_area: { code: "SA41", name: "北海道" },
  },
  {
    code: "Y540",
    large_area: { code: "Z052", name: "岩手" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "宮古・岩手県その他",
    service_area: { code: "SA52", name: "岩手" },
  },
  {
    code: "Y550",
    large_area: { code: "Z053", name: "宮城" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "仙台（仙台駅周辺）",
    service_area: { code: "SA53", name: "宮城" },
  },
  {
    code: "Y554",
    large_area: { code: "Z053", name: "宮城" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "宮城県その他",
    service_area: { code: "SA53", name: "宮城" },
  },
  {
    code: "Y555",
    large_area: { code: "Z053", name: "宮城" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "青葉・宮城野・若林",
    service_area: { code: "SA53", name: "宮城" },
  },
  {
    code: "Y570",
    large_area: { code: "Z056", name: "福島" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "郡山",
    service_area: { code: "SA56", name: "福島" },
  },
  {
    code: "Y580",
    large_area: { code: "Z016", name: "栃木" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "宇都宮",
    service_area: { code: "SA16", name: "栃木" },
  },
  {
    code: "Y581",
    large_area: { code: "Z016", name: "栃木" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "栃木県その他",
    service_area: { code: "SA16", name: "栃木" },
  },
  {
    code: "Y600",
    large_area: { code: "Z074", name: "広島" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "広島市（広島市中心部）",
    service_area: { code: "SA74", name: "広島" },
  },
  {
    code: "Y605",
    large_area: { code: "Z074", name: "広島" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "広島駅・横川・その他広島市内",
    service_area: { code: "SA74", name: "広島" },
  },
  {
    code: "Y610",
    large_area: { code: "Z073", name: "岡山" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "岡山市",
    service_area: { code: "SA73", name: "岡山" },
  },
  {
    code: "Y611",
    large_area: { code: "Z073", name: "岡山" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "倉敷（倉敷市中心部）",
    service_area: { code: "SA73", name: "岡山" },
  },
  {
    code: "Y612",
    large_area: { code: "Z073", name: "岡山" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "倉敷(倉敷市郊外･児島･水島など)",
    service_area: { code: "SA73", name: "岡山" },
  },
  {
    code: "Y620",
    large_area: { code: "Z074", name: "広島" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "福山",
    service_area: { code: "SA74", name: "広島" },
  },
  {
    code: "Y640",
    large_area: { code: "Z075", name: "山口" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "萩・山口県その他",
    service_area: { code: "SA75", name: "山口" },
  },
  {
    code: "Y650",
    large_area: { code: "Z082", name: "香川" },
    large_service_area: { code: "SS80", name: "四国" },
    name: "高松市中心部",
    service_area: { code: "SA82", name: "香川" },
  },
  {
    code: "Y652",
    large_area: { code: "Z082", name: "香川" },
    large_service_area: { code: "SS80", name: "四国" },
    name: "高松市郊外",
    service_area: { code: "SA82", name: "香川" },
  },
  {
    code: "Y660",
    large_area: { code: "Z081", name: "徳島" },
    large_service_area: { code: "SS80", name: "四国" },
    name: "徳島市・徳島市周辺部",
    service_area: { code: "SA81", name: "徳島" },
  },
  {
    code: "Y670",
    large_area: { code: "Z083", name: "愛媛" },
    large_service_area: { code: "SS80", name: "四国" },
    name: "松山",
    service_area: { code: "SA83", name: "愛媛" },
  },
  {
    code: "Y680",
    large_area: { code: "Z084", name: "高知" },
    large_service_area: { code: "SS80", name: "四国" },
    name: "高知市",
    service_area: { code: "SA84", name: "高知" },
  },
  {
    code: "Y690",
    large_area: { code: "Z014", name: "千葉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "松戸・新松戸",
    service_area: { code: "SA14", name: "千葉" },
  },
  {
    code: "Y700",
    large_area: { code: "Z091", name: "福岡" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "博多",
    service_area: { code: "SA91", name: "福岡" },
  },
  {
    code: "Y705",
    large_area: { code: "Z091", name: "福岡" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "中洲・中洲川端",
    service_area: { code: "SA91", name: "福岡" },
  },
  {
    code: "Y706",
    large_area: { code: "Z091", name: "福岡" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "天神・西中洲・春吉",
    service_area: { code: "SA91", name: "福岡" },
  },
  {
    code: "Y710",
    large_area: { code: "Z091", name: "福岡" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "西新・姪浜・その他西エリア",
    service_area: { code: "SA91", name: "福岡" },
  },
  {
    code: "Y711",
    large_area: { code: "Z091", name: "福岡" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "吉塚・香椎・その他東エリア",
    service_area: { code: "SA91", name: "福岡" },
  },
  {
    code: "Y712",
    large_area: { code: "Z091", name: "福岡" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "大名・今泉・警固",
    service_area: { code: "SA91", name: "福岡" },
  },
  {
    code: "Y713",
    large_area: { code: "Z091", name: "福岡" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "薬院･平尾･高砂",
    service_area: { code: "SA91", name: "福岡" },
  },
  {
    code: "Y714",
    large_area: { code: "Z091", name: "福岡" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "大橋･その他南地区",
    service_area: { code: "SA91", name: "福岡" },
  },
  {
    code: "Y730",
    large_area: { code: "Z091", name: "福岡" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "北九州（小倉・門司）",
    service_area: { code: "SA91", name: "福岡" },
  },
  {
    code: "Y731",
    large_area: { code: "Z091", name: "福岡" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "北九州（八幡・黒崎・折尾）",
    service_area: { code: "SA91", name: "福岡" },
  },
  {
    code: "Y732",
    large_area: { code: "Z091", name: "福岡" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "飯塚・筑紫野",
    service_area: { code: "SA91", name: "福岡" },
  },
  {
    code: "Y740",
    large_area: { code: "Z093", name: "長崎" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "長崎市",
    service_area: { code: "SA93", name: "長崎" },
  },
  {
    code: "Y741",
    large_area: { code: "Z093", name: "長崎" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "佐世保・長崎県その他",
    service_area: { code: "SA93", name: "長崎" },
  },
  {
    code: "Y750",
    large_area: { code: "Z095", name: "大分" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "大分市",
    service_area: { code: "SA95", name: "大分" },
  },
  {
    code: "Y751",
    large_area: { code: "Z095", name: "大分" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "湯布院・由布市",
    service_area: { code: "SA95", name: "大分" },
  },
  {
    code: "Y752",
    large_area: { code: "Z095", name: "大分" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "大分県その他",
    service_area: { code: "SA95", name: "大分" },
  },
  {
    code: "Y760",
    large_area: { code: "Z094", name: "熊本" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "熊本市(上通り･下通り･新市街)",
    service_area: { code: "SA94", name: "熊本" },
  },
  {
    code: "Y762",
    large_area: { code: "Z094", name: "熊本" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "熊本市郊外",
    service_area: { code: "SA94", name: "熊本" },
  },
  {
    code: "Y763",
    large_area: { code: "Z094", name: "熊本" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "八代",
    service_area: { code: "SA94", name: "熊本" },
  },
  {
    code: "Y770",
    large_area: { code: "Z096", name: "宮崎" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "宮崎市中心部",
    service_area: { code: "SA96", name: "宮崎" },
  },
  {
    code: "Y771",
    large_area: { code: "Z096", name: "宮崎" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "都城市",
    service_area: { code: "SA96", name: "宮崎" },
  },
  {
    code: "Y772",
    large_area: { code: "Z096", name: "宮崎" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "宮崎県その他",
    service_area: { code: "SA96", name: "宮崎" },
  },
  {
    code: "Y773",
    large_area: { code: "Z096", name: "宮崎" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "宮崎市郊外",
    service_area: { code: "SA96", name: "宮崎" },
  },
  {
    code: "Y777",
    large_area: { code: "Z096", name: "宮崎" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "日南市",
    service_area: { code: "SA96", name: "宮崎" },
  },
  {
    code: "Y780",
    large_area: { code: "Z097", name: "鹿児島" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "鹿児島市　天文館・中央駅・ふ頭",
    service_area: { code: "SA97", name: "鹿児島" },
  },
  {
    code: "Y781",
    large_area: { code: "Z097", name: "鹿児島" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "鹿児島県その他",
    service_area: { code: "SA97", name: "鹿児島" },
  },
  {
    code: "Y785",
    large_area: { code: "Z097", name: "鹿児島" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "騎射場・与次郎",
    service_area: { code: "SA97", name: "鹿児島" },
  },
  {
    code: "Y786",
    large_area: { code: "Z097", name: "鹿児島" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "谷山・宇宿",
    service_area: { code: "SA97", name: "鹿児島" },
  },
  {
    code: "Y787",
    large_area: { code: "Z097", name: "鹿児島" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "鹿児島市その他",
    service_area: { code: "SA97", name: "鹿児島" },
  },
  {
    code: "Y796",
    large_area: { code: "Z065", name: "山梨" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "笛吹市",
    service_area: { code: "SA65", name: "山梨" },
  },
  {
    code: "Y800",
    large_area: { code: "Z032", name: "静岡" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "浜松",
    service_area: { code: "SA32", name: "静岡" },
  },
  {
    code: "Y806",
    large_area: { code: "Z066", name: "長野" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "安曇野",
    service_area: { code: "SA66", name: "長野" },
  },
  {
    code: "Y807",
    large_area: { code: "Z066", name: "長野" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "諏訪・茅野",
    service_area: { code: "SA66", name: "長野" },
  },
  {
    code: "Y808",
    large_area: { code: "Z066", name: "長野" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "長野県その他",
    service_area: { code: "SA66", name: "長野" },
  },
  {
    code: "Y810",
    large_area: { code: "Z031", name: "岐阜" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "岐阜駅周辺・柳ヶ瀬・市役所",
    service_area: { code: "SA31", name: "岐阜" },
  },
  {
    code: "Y811",
    large_area: { code: "Z031", name: "岐阜" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "島・則武・正木・長良",
    service_area: { code: "SA31", name: "岐阜" },
  },
  {
    code: "Y812",
    large_area: { code: "Z031", name: "岐阜" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "県庁～岐南・柳津・岐阜駅以南",
    service_area: { code: "SA31", name: "岐阜" },
  },
  {
    code: "Y813",
    large_area: { code: "Z031", name: "岐阜" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "穂積・北方・大垣",
    service_area: { code: "SA31", name: "岐阜" },
  },
  {
    code: "Y814",
    large_area: { code: "Z031", name: "岐阜" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "日野・芥見・各務原",
    service_area: { code: "SA31", name: "岐阜" },
  },
  {
    code: "Y816",
    large_area: { code: "Z064", name: "福井" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "小浜・福井県その他",
    service_area: { code: "SA64", name: "福井" },
  },
  {
    code: "Y820",
    large_area: { code: "Z061", name: "新潟" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "新潟駅・万代",
    service_area: { code: "SA61", name: "新潟" },
  },
  {
    code: "Y821",
    large_area: { code: "Z061", name: "新潟" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "新潟駅南",
    service_area: { code: "SA61", name: "新潟" },
  },
  {
    code: "Y822",
    large_area: { code: "Z061", name: "新潟" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "古町周辺",
    service_area: { code: "SA61", name: "新潟" },
  },
  {
    code: "Y823",
    large_area: { code: "Z061", name: "新潟" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "新潟東区・北区エリア",
    service_area: { code: "SA61", name: "新潟" },
  },
  {
    code: "Y824",
    large_area: { code: "Z061", name: "新潟" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "新潟西エリア",
    service_area: { code: "SA61", name: "新潟" },
  },
  {
    code: "Y825",
    large_area: { code: "Z061", name: "新潟" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "出来島･女池･桜木･鳥屋野潟周辺",
    service_area: { code: "SA61", name: "新潟" },
  },
  {
    code: "Y826",
    large_area: { code: "Z061", name: "新潟" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "上越",
    service_area: { code: "SA61", name: "新潟" },
  },
  {
    code: "Y827",
    large_area: { code: "Z061", name: "新潟" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "新発田",
    service_area: { code: "SA61", name: "新潟" },
  },
  {
    code: "Y828",
    large_area: { code: "Z061", name: "新潟" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "佐渡・新潟県その他",
    service_area: { code: "SA61", name: "新潟" },
  },
  {
    code: "Y829",
    large_area: { code: "Z061", name: "新潟" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "亀田・新津エリア",
    service_area: { code: "SA61", name: "新潟" },
  },
  {
    code: "Y830",
    large_area: { code: "Z061", name: "新潟" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "長岡",
    service_area: { code: "SA61", name: "新潟" },
  },
  {
    code: "Y831",
    large_area: { code: "Z062", name: "富山" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "黒部・富山県その他",
    service_area: { code: "SA62", name: "富山" },
  },
  {
    code: "Y835",
    large_area: { code: "Z015", name: "茨城" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "結城市",
    service_area: { code: "SA15", name: "茨城" },
  },
  {
    code: "Y840",
    large_area: { code: "Z063", name: "石川" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "金沢(片町･香林坊･にし茶屋周辺)",
    service_area: { code: "SA63", name: "石川" },
  },
  {
    code: "Y841",
    large_area: { code: "Z063", name: "石川" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "金沢(金沢駅･近江町･ひがし茶屋)",
    service_area: { code: "SA63", name: "石川" },
  },
  {
    code: "Y842",
    large_area: { code: "Z063", name: "石川" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "金沢市他・野々市・白山・内灘",
    service_area: { code: "SA63", name: "石川" },
  },
  {
    code: "Y843",
    large_area: { code: "Z017", name: "群馬" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "桐生市・みどり市",
    service_area: { code: "SA17", name: "群馬" },
  },
  {
    code: "Y844",
    large_area: { code: "Z017", name: "群馬" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "館林・大泉町・邑楽町",
    service_area: { code: "SA17", name: "群馬" },
  },
  {
    code: "Y845",
    large_area: { code: "Z013", name: "埼玉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "所沢",
    service_area: { code: "SA13", name: "埼玉" },
  },
  {
    code: "Y846",
    large_area: { code: "Z013", name: "埼玉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "西武新宿線（航空公園～南大塚）",
    service_area: { code: "SA13", name: "埼玉" },
  },
  {
    code: "Y847",
    large_area: { code: "Z013", name: "埼玉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "東武東上線 和光市～新河岸･新座",
    service_area: { code: "SA13", name: "埼玉" },
  },
  {
    code: "Y848",
    large_area: { code: "Z032", name: "静岡" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "伊豆・伊東・下田",
    service_area: { code: "SA32", name: "静岡" },
  },
  {
    code: "Y849",
    large_area: { code: "Z032", name: "静岡" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "焼津・藤枝・掛川",
    service_area: { code: "SA32", name: "静岡" },
  },
  {
    code: "Y850",
    large_area: { code: "Z024", name: "兵庫" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "姫路",
    service_area: { code: "SA24", name: "兵庫" },
  },
  {
    code: "Y851",
    large_area: { code: "Z024", name: "兵庫" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "加古川",
    service_area: { code: "SA24", name: "兵庫" },
  },
  {
    code: "Y852",
    large_area: { code: "Z011", name: "東京" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "東京都その他",
    service_area: { code: "SA11", name: "東京" },
  },
  {
    code: "Y853",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "鎌倉・江の島",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y854",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "小田原・箱根・湯河原・真鶴",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y855",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "横須賀中央・三浦・久里浜・汐入",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y856",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "逗子・葉山",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y857",
    large_area: { code: "Z012", name: "神奈川" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "神奈川県その他",
    service_area: { code: "SA12", name: "神奈川" },
  },
  {
    code: "Y858",
    large_area: { code: "Z014", name: "千葉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "銚子・旭",
    service_area: { code: "SA14", name: "千葉" },
  },
  {
    code: "Y859",
    large_area: { code: "Z014", name: "千葉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "木更津・市原",
    service_area: { code: "SA14", name: "千葉" },
  },
  {
    code: "Y860",
    large_area: { code: "Z013", name: "埼玉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "西武池袋線（小手指～飯能）",
    service_area: { code: "SA13", name: "埼玉" },
  },
  {
    code: "Y861",
    large_area: { code: "Z013", name: "埼玉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "川越",
    service_area: { code: "SA13", name: "埼玉" },
  },
  {
    code: "Y862",
    large_area: { code: "Z013", name: "埼玉" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "春日部・越谷・草加・三郷",
    service_area: { code: "SA13", name: "埼玉" },
  },
  {
    code: "Y863",
    large_area: { code: "Z016", name: "栃木" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "日光・鹿沼",
    service_area: { code: "SA16", name: "栃木" },
  },
  {
    code: "Y864",
    large_area: { code: "Z016", name: "栃木" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "那須・塩原",
    service_area: { code: "SA16", name: "栃木" },
  },
  {
    code: "Y865",
    large_area: { code: "Z016", name: "栃木" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "小山市・栃木市",
    service_area: { code: "SA16", name: "栃木" },
  },
  {
    code: "Y866",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "九条･西九条･弁天町･大正･住之江",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y867",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "枚方・寝屋川・守口・門真",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y868",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "大阪府その他",
    service_area: { code: "SA23", name: "大阪" },
  },
  {
    code: "Y869",
    large_area: { code: "Z022", name: "京都" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "宮津・京丹後・京都府その他",
    service_area: { code: "SA22", name: "京都" },
  },
  {
    code: "Y870",
    large_area: { code: "Z024", name: "兵庫" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "淡路島",
    service_area: { code: "SA24", name: "兵庫" },
  },
  {
    code: "Y871",
    large_area: { code: "Z024", name: "兵庫" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "西宮・芦屋・宝塚",
    service_area: { code: "SA24", name: "兵庫" },
  },
  {
    code: "Y872",
    large_area: { code: "Z024", name: "兵庫" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "城崎・豊岡",
    service_area: { code: "SA24", name: "兵庫" },
  },
  {
    code: "Y873",
    large_area: { code: "Z024", name: "兵庫" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "北区・有馬温泉・三田",
    service_area: { code: "SA24", name: "兵庫" },
  },
  {
    code: "Y874",
    large_area: { code: "Z024", name: "兵庫" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "尼崎",
    service_area: { code: "SA24", name: "兵庫" },
  },
  {
    code: "Y875",
    large_area: { code: "Z033", name: "愛知" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "安城・刈谷・岡崎・知立・蒲郡",
    service_area: { code: "SA33", name: "愛知" },
  },
  {
    code: "Y876",
    large_area: { code: "Z032", name: "静岡" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "熱海",
    service_area: { code: "SA32", name: "静岡" },
  },
  {
    code: "Y877",
    large_area: { code: "Z032", name: "静岡" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "富士宮",
    service_area: { code: "SA32", name: "静岡" },
  },
  {
    code: "Y878",
    large_area: { code: "Z032", name: "静岡" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "静岡県その他",
    service_area: { code: "SA32", name: "静岡" },
  },
  {
    code: "Y879",
    large_area: { code: "Z031", name: "岐阜" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "高山・中津川",
    service_area: { code: "SA31", name: "岐阜" },
  },
  {
    code: "Y880",
    large_area: { code: "Z031", name: "岐阜" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "多治見・土岐",
    service_area: { code: "SA31", name: "岐阜" },
  },
  {
    code: "Y881",
    large_area: { code: "Z061", name: "新潟" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "燕三条",
    service_area: { code: "SA61", name: "新潟" },
  },
  {
    code: "Y882",
    large_area: { code: "Z063", name: "石川" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "輪島・七尾・加賀・石川県その他",
    service_area: { code: "SA63", name: "石川" },
  },
  {
    code: "Y883",
    large_area: { code: "Z041", name: "北海道" },
    large_service_area: { code: "SS40", name: "北海道" },
    name: "函館",
    service_area: { code: "SA41", name: "北海道" },
  },
  {
    code: "Y884",
    large_area: { code: "Z041", name: "北海道" },
    large_service_area: { code: "SS40", name: "北海道" },
    name: "小樽・千歳・苫小牧・札幌近郊",
    service_area: { code: "SA41", name: "北海道" },
  },
  {
    code: "Y885",
    large_area: { code: "Z041", name: "北海道" },
    large_service_area: { code: "SS40", name: "北海道" },
    name: "帯広・釧路・北見・河東郡",
    service_area: { code: "SA41", name: "北海道" },
  },
  {
    code: "Y886",
    large_area: { code: "Z053", name: "宮城" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "仙台（国分町・一番町周辺）",
    service_area: { code: "SA53", name: "宮城" },
  },
  {
    code: "Y887",
    large_area: { code: "Z053", name: "宮城" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "泉中央",
    service_area: { code: "SA53", name: "宮城" },
  },
  {
    code: "Y888",
    large_area: { code: "Z053", name: "宮城" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "長町",
    service_area: { code: "SA53", name: "宮城" },
  },
  {
    code: "Y889",
    large_area: { code: "Z053", name: "宮城" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "大崎市",
    service_area: { code: "SA53", name: "宮城" },
  },
  {
    code: "Y890",
    large_area: { code: "Z056", name: "福島" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "会津若松",
    service_area: { code: "SA56", name: "福島" },
  },
  {
    code: "Y891",
    large_area: { code: "Z056", name: "福島" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "喜多方",
    service_area: { code: "SA56", name: "福島" },
  },
  {
    code: "Y892",
    large_area: { code: "Z056", name: "福島" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "福島市",
    service_area: { code: "SA56", name: "福島" },
  },
  {
    code: "Y893",
    large_area: { code: "Z056", name: "福島" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "いわき・福島県その他",
    service_area: { code: "SA56", name: "福島" },
  },
  {
    code: "Y894",
    large_area: { code: "Z074", name: "広島" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "尾道",
    service_area: { code: "SA74", name: "広島" },
  },
  {
    code: "Y895",
    large_area: { code: "Z073", name: "岡山" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "備前・岡山県その他",
    service_area: { code: "SA73", name: "岡山" },
  },
  {
    code: "Y896",
    large_area: { code: "Z082", name: "香川" },
    large_service_area: { code: "SS80", name: "四国" },
    name: "丸亀･坂出･宇多津･善通寺･多度津",
    service_area: { code: "SA82", name: "香川" },
  },
  {
    code: "Y897",
    large_area: { code: "Z081", name: "徳島" },
    large_service_area: { code: "SS80", name: "四国" },
    name: "徳島県その他",
    service_area: { code: "SA81", name: "徳島" },
  },
  {
    code: "Y898",
    large_area: { code: "Z083", name: "愛媛" },
    large_service_area: { code: "SS80", name: "四国" },
    name: "今治",
    service_area: { code: "SA83", name: "愛媛" },
  },
  {
    code: "Y899",
    large_area: { code: "Z084", name: "高知" },
    large_service_area: { code: "SS80", name: "四国" },
    name: "高知県その他",
    service_area: { code: "SA84", name: "高知" },
  },
  {
    code: "Y900",
    large_area: { code: "Z091", name: "福岡" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "久留米",
    service_area: { code: "SA91", name: "福岡" },
  },
  {
    code: "Y901",
    large_area: { code: "Z091", name: "福岡" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "福岡県その他",
    service_area: { code: "SA91", name: "福岡" },
  },
  {
    code: "Y902",
    large_area: { code: "Z093", name: "長崎" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "大村市・諫早市",
    service_area: { code: "SA93", name: "長崎" },
  },
  {
    code: "Y903",
    large_area: { code: "Z095", name: "大分" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "別府",
    service_area: { code: "SA95", name: "大分" },
  },
  {
    code: "Y904",
    large_area: { code: "Z095", name: "大分" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "中津市",
    service_area: { code: "SA95", name: "大分" },
  },
  {
    code: "Y905",
    large_area: { code: "Z094", name: "熊本" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "阿蘇",
    service_area: { code: "SA94", name: "熊本" },
  },
  {
    code: "Y906",
    large_area: { code: "Z094", name: "熊本" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "天草・熊本県その他",
    service_area: { code: "SA94", name: "熊本" },
  },
  {
    code: "Y907",
    large_area: { code: "Z096", name: "宮崎" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "延岡市・日向市",
    service_area: { code: "SA96", name: "宮崎" },
  },
  {
    code: "Y908",
    large_area: { code: "Z097", name: "鹿児島" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "奄美・屋久島",
    service_area: { code: "SA97", name: "鹿児島" },
  },
  {
    code: "Y909",
    large_area: { code: "Z097", name: "鹿児島" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "霧島市",
    service_area: { code: "SA97", name: "鹿児島" },
  },
  {
    code: "Y910",
    large_area: { code: "Z051", name: "青森" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "青森市",
    service_area: { code: "SA51", name: "青森" },
  },
  {
    code: "Y911",
    large_area: { code: "Z051", name: "青森" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "弘前",
    service_area: { code: "SA51", name: "青森" },
  },
  {
    code: "Y912",
    large_area: { code: "Z051", name: "青森" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "八戸",
    service_area: { code: "SA51", name: "青森" },
  },
  {
    code: "Y913",
    large_area: { code: "Z051", name: "青森" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "五所川原・青森西部",
    service_area: { code: "SA51", name: "青森" },
  },
  {
    code: "Y914",
    large_area: { code: "Z051", name: "青森" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "十和田・三沢・おいらせ町",
    service_area: { code: "SA51", name: "青森" },
  },
  {
    code: "Y915",
    large_area: { code: "Z052", name: "岩手" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "盛岡",
    service_area: { code: "SA52", name: "岩手" },
  },
  {
    code: "Y916",
    large_area: { code: "Z052", name: "岩手" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "花巻・北上・奥州・一関",
    service_area: { code: "SA52", name: "岩手" },
  },
  {
    code: "Y917",
    large_area: { code: "Z054", name: "秋田" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "秋田市",
    service_area: { code: "SA54", name: "秋田" },
  },
  {
    code: "Y918",
    large_area: { code: "Z054", name: "秋田" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "仙北市・秋田県北部",
    service_area: { code: "SA54", name: "秋田" },
  },
  {
    code: "Y919",
    large_area: { code: "Z054", name: "秋田" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "横手・秋田県南部",
    service_area: { code: "SA54", name: "秋田" },
  },
  {
    code: "Y920",
    large_area: { code: "Z055", name: "山形" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "山形市",
    service_area: { code: "SA55", name: "山形" },
  },
  {
    code: "Y921",
    large_area: { code: "Z055", name: "山形" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "米沢",
    service_area: { code: "SA55", name: "山形" },
  },
  {
    code: "Y922",
    large_area: { code: "Z055", name: "山形" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "酒田・鶴岡",
    service_area: { code: "SA55", name: "山形" },
  },
  {
    code: "Y923",
    large_area: { code: "Z055", name: "山形" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "山形県その他",
    service_area: { code: "SA55", name: "山形" },
  },
  {
    code: "Y924",
    large_area: { code: "Z015", name: "茨城" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "水戸",
    service_area: { code: "SA15", name: "茨城" },
  },
  {
    code: "Y925",
    large_area: { code: "Z015", name: "茨城" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "つくば",
    service_area: { code: "SA15", name: "茨城" },
  },
  {
    code: "Y926",
    large_area: { code: "Z015", name: "茨城" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "日立・ひたちなか",
    service_area: { code: "SA15", name: "茨城" },
  },
  {
    code: "Y927",
    large_area: { code: "Z015", name: "茨城" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "笠間・常陸太田・茨城県北部他",
    service_area: { code: "SA15", name: "茨城" },
  },
  {
    code: "Y928",
    large_area: { code: "Z015", name: "茨城" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "鹿嶋・鉾田・茨城県南部他",
    service_area: { code: "SA15", name: "茨城" },
  },
  {
    code: "Y929",
    large_area: { code: "Z017", name: "群馬" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "前橋",
    service_area: { code: "SA17", name: "群馬" },
  },
  {
    code: "Y930",
    large_area: { code: "Z017", name: "群馬" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "草津・嬬恋",
    service_area: { code: "SA17", name: "群馬" },
  },
  {
    code: "Y931",
    large_area: { code: "Z017", name: "群馬" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "伊香保・群馬県その他",
    service_area: { code: "SA17", name: "群馬" },
  },
  {
    code: "Y932",
    large_area: { code: "Z062", name: "富山" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "富山市",
    service_area: { code: "SA62", name: "富山" },
  },
  {
    code: "Y933",
    large_area: { code: "Z062", name: "富山" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "高岡",
    service_area: { code: "SA62", name: "富山" },
  },
  {
    code: "Y934",
    large_area: { code: "Z064", name: "福井" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "福井市",
    service_area: { code: "SA64", name: "福井" },
  },
  {
    code: "Y935",
    large_area: { code: "Z064", name: "福井" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "敦賀",
    service_area: { code: "SA64", name: "福井" },
  },
  {
    code: "Y936",
    large_area: { code: "Z065", name: "山梨" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "富士吉田・河口湖",
    service_area: { code: "SA65", name: "山梨" },
  },
  {
    code: "Y937",
    large_area: { code: "Z065", name: "山梨" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "北杜市",
    service_area: { code: "SA65", name: "山梨" },
  },
  {
    code: "Y938",
    large_area: { code: "Z065", name: "山梨" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "山梨県その他",
    service_area: { code: "SA65", name: "山梨" },
  },
  {
    code: "Y939",
    large_area: { code: "Z066", name: "長野" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "長野市",
    service_area: { code: "SA66", name: "長野" },
  },
  {
    code: "Y940",
    large_area: { code: "Z066", name: "長野" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "松本市",
    service_area: { code: "SA66", name: "長野" },
  },
  {
    code: "Y941",
    large_area: { code: "Z066", name: "長野" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "軽井沢",
    service_area: { code: "SA66", name: "長野" },
  },
  {
    code: "Y942",
    large_area: { code: "Z066", name: "長野" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "上田・佐久",
    service_area: { code: "SA66", name: "長野" },
  },
  {
    code: "Y943",
    large_area: { code: "Z034", name: "三重" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "伊勢",
    service_area: { code: "SA34", name: "三重" },
  },
  {
    code: "Y944",
    large_area: { code: "Z034", name: "三重" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "松阪",
    service_area: { code: "SA34", name: "三重" },
  },
  {
    code: "Y945",
    large_area: { code: "Z034", name: "三重" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "桑名",
    service_area: { code: "SA34", name: "三重" },
  },
  {
    code: "Y946",
    large_area: { code: "Z021", name: "滋賀" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "大津",
    service_area: { code: "SA21", name: "滋賀" },
  },
  {
    code: "Y947",
    large_area: { code: "Z021", name: "滋賀" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "長浜市・彦根市",
    service_area: { code: "SA21", name: "滋賀" },
  },
  {
    code: "Y948",
    large_area: { code: "Z021", name: "滋賀" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "近江八幡市・東近江市",
    service_area: { code: "SA21", name: "滋賀" },
  },
  {
    code: "Y949",
    large_area: { code: "Z025", name: "奈良" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "奈良市",
    service_area: { code: "SA25", name: "奈良" },
  },
  {
    code: "Y950",
    large_area: { code: "Z025", name: "奈良" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "天理市・橿原市",
    service_area: { code: "SA25", name: "奈良" },
  },
  {
    code: "Y951",
    large_area: { code: "Z026", name: "和歌山" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "和歌山市",
    service_area: { code: "SA26", name: "和歌山" },
  },
  {
    code: "Y952",
    large_area: { code: "Z026", name: "和歌山" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "田辺市",
    service_area: { code: "SA26", name: "和歌山" },
  },
  {
    code: "Y953",
    large_area: { code: "Z071", name: "鳥取" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "鳥取市",
    service_area: { code: "SA71", name: "鳥取" },
  },
  {
    code: "Y954",
    large_area: { code: "Z071", name: "鳥取" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "米子市",
    service_area: { code: "SA71", name: "鳥取" },
  },
  {
    code: "Y955",
    large_area: { code: "Z072", name: "島根" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "松江",
    service_area: { code: "SA72", name: "島根" },
  },
  {
    code: "Y956",
    large_area: { code: "Z072", name: "島根" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "出雲市",
    service_area: { code: "SA72", name: "島根" },
  },
  {
    code: "Y957",
    large_area: { code: "Z075", name: "山口" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "下関",
    service_area: { code: "SA75", name: "山口" },
  },
  {
    code: "Y958",
    large_area: { code: "Z075", name: "山口" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "山口市",
    service_area: { code: "SA75", name: "山口" },
  },
  {
    code: "Y959",
    large_area: { code: "Z092", name: "佐賀" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "佐賀市",
    service_area: { code: "SA92", name: "佐賀" },
  },
  {
    code: "Y960",
    large_area: { code: "Z092", name: "佐賀" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "佐賀県その他",
    service_area: { code: "SA92", name: "佐賀" },
  },
  {
    code: "Y961",
    large_area: { code: "Z098", name: "沖縄" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "那覇",
    service_area: { code: "SA98", name: "沖縄" },
  },
  {
    code: "Y962",
    large_area: { code: "Z098", name: "沖縄" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "糸満・豊見城・南風原・南城",
    service_area: { code: "SA98", name: "沖縄" },
  },
  {
    code: "Y963",
    large_area: { code: "Z098", name: "沖縄" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "石垣島・宮古島・沖縄離島",
    service_area: { code: "SA98", name: "沖縄" },
  },
  {
    code: "Y964",
    large_area: { code: "Z098", name: "沖縄" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "名護・恩納村・本部町",
    service_area: { code: "SA98", name: "沖縄" },
  },
  {
    code: "Y965",
    large_area: { code: "Z098", name: "沖縄" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "読谷･北谷･宜野湾･浦添･嘉手納",
    service_area: { code: "SA98", name: "沖縄" },
  },
  {
    code: "Y966",
    large_area: { code: "Z017", name: "群馬" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "高崎",
    service_area: { code: "SA17", name: "群馬" },
  },
  {
    code: "Y967",
    large_area: { code: "Z017", name: "群馬" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "伊勢崎・玉村",
    service_area: { code: "SA17", name: "群馬" },
  },
  {
    code: "Y968",
    large_area: { code: "Z017", name: "群馬" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "太田市",
    service_area: { code: "SA17", name: "群馬" },
  },
  {
    code: "Y969",
    large_area: { code: "Z015", name: "茨城" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "土浦",
    service_area: { code: "SA15", name: "茨城" },
  },
  {
    code: "Y970",
    large_area: { code: "Z025", name: "奈良" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "大和郡山市・生駒市",
    service_area: { code: "SA25", name: "奈良" },
  },
  {
    code: "Y971",
    large_area: { code: "Z034", name: "三重" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "四日市",
    service_area: { code: "SA34", name: "三重" },
  },
  {
    code: "Y972",
    large_area: { code: "Z064", name: "福井" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "坂井市",
    service_area: { code: "SA64", name: "福井" },
  },
  {
    code: "Y973",
    large_area: { code: "Z065", name: "山梨" },
    large_service_area: { code: "SS60", name: "北陸・甲信越" },
    name: "甲府",
    service_area: { code: "SA65", name: "山梨" },
  },
  {
    code: "Y974",
    large_area: { code: "Z092", name: "佐賀" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "唐津",
    service_area: { code: "SA92", name: "佐賀" },
  },
  {
    code: "Y975",
    large_area: { code: "Z083", name: "愛媛" },
    large_service_area: { code: "SS80", name: "四国" },
    name: "宇和島･東予･南予･愛媛県その他",
    service_area: { code: "SA83", name: "愛媛" },
  },
  {
    code: "Y976",
    large_area: { code: "Z098", name: "沖縄" },
    large_service_area: { code: "SS90", name: "九州・沖縄" },
    name: "沖縄市・うるま・西原・北中城",
    service_area: { code: "SA98", name: "沖縄" },
  },
  {
    code: "Y977",
    large_area: { code: "Z051", name: "青森" },
    large_service_area: { code: "SS50", name: "東北" },
    name: "むつ市・青森東部",
    service_area: { code: "SA51", name: "青森" },
  },
  {
    code: "Y979",
    large_area: { code: "Z016", name: "栃木" },
    large_service_area: { code: "SS10", name: "関東" },
    name: "足利市・佐野市",
    service_area: { code: "SA16", name: "栃木" },
  },
  {
    code: "Y980",
    large_area: { code: "Z083", name: "愛媛" },
    large_service_area: { code: "SS80", name: "四国" },
    name: "新居浜・西条",
    service_area: { code: "SA83", name: "愛媛" },
  },
  {
    code: "Y981",
    large_area: { code: "Z082", name: "香川" },
    large_service_area: { code: "SS80", name: "四国" },
    name: "坂出・香川県その他",
    service_area: { code: "SA82", name: "香川" },
  },
  {
    code: "Y982",
    large_area: { code: "Z075", name: "山口" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "宇部市",
    service_area: { code: "SA75", name: "山口" },
  },
  {
    code: "Y983",
    large_area: { code: "Z075", name: "山口" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "周南市・下松市",
    service_area: { code: "SA75", name: "山口" },
  },
  {
    code: "Y984",
    large_area: { code: "Z075", name: "山口" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "岩国",
    service_area: { code: "SA75", name: "山口" },
  },
  {
    code: "Y985",
    large_area: { code: "Z075", name: "山口" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "防府",
    service_area: { code: "SA75", name: "山口" },
  },
  {
    code: "Y986",
    large_area: { code: "Z074", name: "広島" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "呉",
    service_area: { code: "SA74", name: "広島" },
  },
  {
    code: "Y987",
    large_area: { code: "Z074", name: "広島" },
    large_service_area: { code: "SS70", name: "中国" },
    name: "広島県その他",
    service_area: { code: "SA74", name: "広島" },
  },
  {
    code: "Y988",
    large_area: { code: "Z031", name: "岐阜" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "下呂・岐阜県その他",
    service_area: { code: "SA31", name: "岐阜" },
  },
  {
    code: "Y989",
    large_area: { code: "Z034", name: "三重" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "津",
    service_area: { code: "SA34", name: "三重" },
  },
  {
    code: "Y990",
    large_area: { code: "Z034", name: "三重" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "鈴鹿",
    service_area: { code: "SA34", name: "三重" },
  },
  {
    code: "Y991",
    large_area: { code: "Z034", name: "三重" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "鳥羽・志摩",
    service_area: { code: "SA34", name: "三重" },
  },
  {
    code: "Y992",
    large_area: { code: "Z033", name: "愛知" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "半田・知多・碧南・西尾",
    service_area: { code: "SA33", name: "愛知" },
  },
  {
    code: "Y993",
    large_area: { code: "Z033", name: "愛知" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "春日井・小牧・一宮・江南・瀬戸",
    service_area: { code: "SA33", name: "愛知" },
  },
  {
    code: "Y994",
    large_area: { code: "Z033", name: "愛知" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "豊橋・豊川",
    service_area: { code: "SA33", name: "愛知" },
  },
  {
    code: "Y995",
    large_area: { code: "Z033", name: "愛知" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "愛知県その他",
    service_area: { code: "SA33", name: "愛知" },
  },
  {
    code: "Y996",
    large_area: { code: "Z024", name: "兵庫" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "兵庫県その他",
    service_area: { code: "SA24", name: "兵庫" },
  },
  {
    code: "Y997",
    large_area: { code: "Z032", name: "静岡" },
    large_service_area: { code: "SS30", name: "東海" },
    name: "御殿場・富士・沼津・三島",
    service_area: { code: "SA32", name: "静岡" },
  },
  {
    code: "Y998",
    large_area: { code: "Z023", name: "大阪" },
    large_service_area: { code: "SS20", name: "関西" },
    name: "箕面・池田",
    service_area: { code: "SA23", name: "大阪" },
  },
];
